// PDF Export Utility
// Generate professional PDF reports for SEO analysis

import jsPDF from 'jspdf';
import 'jspdf-autotable';

class PDFExportService {
    constructor() {
        this.whiteLabel = localStorage.getItem('whiteLabel') === 'true';
    }

    // Set white-label mode
    setWhiteLabel(enabled) {
        this.whiteLabel = enabled;
        localStorage.setItem('whiteLabel', enabled.toString());
    }

    // Get branding info
    getBranding() {
        if (this.whiteLabel) {
            return {
                title: 'SEO Analysis Report',
                footer: '',
                logo: null
            };
        }
        return {
            title: 'DataEngineer Hub - SEO Analysis Report',
            footer: 'Generated by DataEngineer Hub SEO Toolkit',
            logo: null // Can add logo later
        };
    }

    // Export single URL analysis to PDF
    exportSingleAnalysis(result, filename = 'seo-analysis.pdf') {
        const doc = new jsPDF();
        const branding = this.getBranding();
        let yPos = 20;

        // Header
        doc.setFontSize(20);
        doc.setTextColor(59, 130, 246); // Blue
        doc.text(branding.title, 20, yPos);
        yPos += 10;

        // URL
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`URL: ${result.url}`, 20, yPos);
        yPos += 10;

        doc.setTextColor(150);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPos);
        yPos += 15;

        // Score Section
        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text('Optimization Score', 20, yPos);
        yPos += 10;

        // Score box
        const scoreColor = result.score >= 85 ? [34, 197, 94] : result.score >= 70 ? [234, 179, 8] : [239, 68, 68];
        doc.setFillColor(...scoreColor);
        doc.roundedRect(20, yPos, 40, 15, 3, 3, 'F');
        doc.setFontSize(24);
        doc.setTextColor(255);
        doc.text(`${result.score}`, 30, yPos + 11);
        yPos += 25;

        // Quick Stats
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text('Quick Statistics', 20, yPos);
        yPos += 8;

        const stats = [
            ['Metric', 'Value'],
            ['Word Count', result.wordCount?.toString() || '0'],
            ['Statistics', result.statistics?.toString() || '0'],
            ['Questions', result.questions?.toString() || '0'],
            ['Authority Links', result.authorityLinks?.toString() || '0'],
            ['Internal Links', result.internalLinks?.toString() || '0'],
            ['External Links', result.externalLinks?.toString() || '0'],
            ['Data Tables', result.tables?.toString() || '0'],
            ['Code Examples', result.codeBlocks?.toString() || '0']
        ];

        doc.autoTable({
            startY: yPos,
            head: [stats[0]],
            body: stats.slice(1),
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] },
            margin: { left: 20, right: 20 }
        });

        yPos = doc.lastAutoTable.finalY + 15;

        // AI Visibility Score
        if (result.aiVisibility) {
            if (yPos > 250) {
                doc.addPage();
                yPos = 20;
            }

            doc.setFontSize(14);
            doc.setTextColor(147, 51, 234); // Purple
            doc.text('AI Visibility Score', 20, yPos);
            yPos += 8;

            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Citation Probability: ${result.aiVisibility.citationProbability} (${result.aiVisibility.score}%)`, 20, yPos);
            yPos += 10;

            const factors = [
                ['Factor', 'Impact', 'Status'],
                ...result.aiVisibility.factors.map(f => [f.factor, f.impact, f.status])
            ];

            doc.autoTable({
                startY: yPos,
                head: [factors[0]],
                body: factors.slice(1),
                theme: 'striped',
                headStyles: { fillColor: [147, 51, 234] },
                margin: { left: 20, right: 20 }
            });

            yPos = doc.lastAutoTable.finalY + 15;
        }

        // Strengths
        if (result.strengths && result.strengths.length > 0) {
            if (yPos > 250) {
                doc.addPage();
                yPos = 20;
            }

            doc.setFontSize(14);
            doc.setTextColor(34, 197, 94); // Green
            doc.text(`Strengths (${result.strengths.length})`, 20, yPos);
            yPos += 8;

            doc.setFontSize(9);
            doc.setTextColor(0);
            result.strengths.forEach((strength, idx) => {
                if (yPos > 280) {
                    doc.addPage();
                    yPos = 20;
                }
                doc.text(`✓ ${strength}`, 25, yPos);
                yPos += 6;
            });
            yPos += 10;
        }

        // Issues
        if (result.issues && result.issues.length > 0) {
            if (yPos > 250) {
                doc.addPage();
                yPos = 20;
            }

            doc.setFontSize(14);
            doc.setTextColor(239, 68, 68); // Red
            doc.text(`Issues Found (${result.issues.length})`, 20, yPos);
            yPos += 8;

            doc.setFontSize(9);
            doc.setTextColor(0);
            result.issues.forEach((issue, idx) => {
                if (yPos > 280) {
                    doc.addPage();
                    yPos = 20;
                }
                doc.text(`✗ ${issue}`, 25, yPos);
                yPos += 6;
            });
            yPos += 10;
        }

        // Recommendations
        if (result.recommendations && result.recommendations.length > 0) {
            doc.addPage();
            yPos = 20;

            doc.setFontSize(16);
            doc.setTextColor(0);
            doc.text('Recommendations', 20, yPos);
            yPos += 10;

            result.recommendations.forEach((rec, idx) => {
                if (yPos > 260) {
                    doc.addPage();
                    yPos = 20;
                }

                // Priority badge
                const priorityColor = rec.priority === 'HIGH' ? [239, 68, 68] : rec.priority === 'MEDIUM' ? [234, 179, 8] : [59, 130, 246];
                doc.setFillColor(...priorityColor);
                doc.roundedRect(20, yPos - 3, 15, 6, 1, 1, 'F');
                doc.setFontSize(8);
                doc.setTextColor(255);
                doc.text(rec.priority, 22, yPos + 1);

                // Type
                doc.setFontSize(11);
                doc.setTextColor(0);
                doc.text(rec.type, 40, yPos + 1);
                yPos += 8;

                // Issue
                doc.setFontSize(9);
                doc.setTextColor(100);
                const issueLines = doc.splitTextToSize(`Issue: ${rec.issue}`, 170);
                doc.text(issueLines, 25, yPos);
                yPos += issueLines.length * 5;

                // Action
                const actionLines = doc.splitTextToSize(`Action: ${rec.action}`, 170);
                doc.text(actionLines, 25, yPos);
                yPos += actionLines.length * 5;

                // Impact
                doc.setTextColor(59, 130, 246);
                const impactLines = doc.splitTextToSize(`Impact: ${rec.impact}`, 170);
                doc.text(impactLines, 25, yPos);
                yPos += impactLines.length * 5 + 8;
            });
        }

        // Footer
        if (branding.footer) {
            const pageCount = doc.internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text(branding.footer, 20, 285);
                doc.text(`Page ${i} of ${pageCount}`, 180, 285);
            }
        }

        // Save
        doc.save(filename);
    }

    // Export bulk scan results to PDF
    exportBulkScan(results, filename = 'bulk-seo-scan.pdf') {
        const doc = new jsPDF();
        const branding = this.getBranding();
        let yPos = 20;

        // Header
        doc.setFontSize(20);
        doc.setTextColor(59, 130, 246);
        doc.text(branding.title, 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text(`Bulk Scan Report - ${results.length} URLs`, 20, yPos);
        yPos += 5;
        doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPos);
        yPos += 15;

        // Summary Statistics
        const avgScore = Math.round(results.reduce((sum, r) => sum + (r.score || 0), 0) / results.length);
        const highScores = results.filter(r => r.score >= 85).length;
        const mediumScores = results.filter(r => r.score >= 70 && r.score < 85).length;
        const lowScores = results.filter(r => r.score < 70).length;

        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.text('Summary', 20, yPos);
        yPos += 8;

        const summary = [
            ['Metric', 'Value'],
            ['Total URLs Scanned', results.length.toString()],
            ['Average Score', `${avgScore}/100`],
            ['High Scores (85+)', highScores.toString()],
            ['Medium Scores (70-84)', mediumScores.toString()],
            ['Low Scores (<70)', lowScores.toString()]
        ];

        doc.autoTable({
            startY: yPos,
            head: [summary[0]],
            body: summary.slice(1),
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] },
            margin: { left: 20, right: 20 }
        });

        yPos = doc.lastAutoTable.finalY + 15;

        // Detailed Results
        doc.addPage();
        yPos = 20;

        doc.setFontSize(14);
        doc.text('Detailed Results', 20, yPos);
        yPos += 10;

        const tableData = results.map(r => [
            r.title?.substring(0, 40) || 'Untitled',
            r.score?.toString() || '0',
            r.wordCount?.toString() || '0',
            r.issues?.length?.toString() || '0'
        ]);

        doc.autoTable({
            startY: yPos,
            head: [['Page Title', 'Score', 'Words', 'Issues']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] },
            margin: { left: 20, right: 20 },
            columnStyles: {
                0: { cellWidth: 80 },
                1: { cellWidth: 30, halign: 'center' },
                2: { cellWidth: 30, halign: 'center' },
                3: { cellWidth: 30, halign: 'center' }
            }
        });

        // Footer
        if (branding.footer) {
            const pageCount = doc.internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text(branding.footer, 20, 285);
                doc.text(`Page ${i} of ${pageCount}`, 180, 285);
            }
        }

        doc.save(filename);
    }

    // Export comparison to PDF
    exportComparison(result1, result2, filename = 'seo-comparison.pdf') {
        const doc = new jsPDF();
        const branding = this.getBranding();
        let yPos = 20;

        // Header
        doc.setFontSize(20);
        doc.setTextColor(147, 51, 234); // Purple
        doc.text('SEO Comparison Report', 20, yPos);
        yPos += 10;

        doc.setFontSize(9);
        doc.setTextColor(150);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 20, yPos);
        yPos += 15;

        // URLs
        doc.setFontSize(10);
        doc.setTextColor(0);
        doc.text('Your URL:', 20, yPos);
        doc.setTextColor(100);
        doc.text(result1.url, 20, yPos + 5);
        yPos += 12;

        doc.setTextColor(0);
        doc.text('Competitor URL:', 20, yPos);
        doc.setTextColor(100);
        doc.text(result2.url, 20, yPos + 5);
        yPos += 15;

        // Comparison Table
        const comparison = [
            ['Metric', 'You', 'Competitor', 'Difference'],
            ['Score', result1.score?.toString() || '0', result2.score?.toString() || '0', (result1.score - result2.score).toString()],
            ['Word Count', result1.wordCount?.toString() || '0', result2.wordCount?.toString() || '0', (result1.wordCount - result2.wordCount).toString()],
            ['Statistics', result1.statistics?.toString() || '0', result2.statistics?.toString() || '0', (result1.statistics - result2.statistics).toString()],
            ['Questions', result1.questions?.toString() || '0', result2.questions?.toString() || '0', (result1.questions - result2.questions).toString()],
            ['Authority Links', result1.authorityLinks?.toString() || '0', result2.authorityLinks?.toString() || '0', (result1.authorityLinks - result2.authorityLinks).toString()],
            ['Internal Links', result1.internalLinks?.toString() || '0', result2.internalLinks?.toString() || '0', (result1.internalLinks - result2.internalLinks).toString()],
            ['External Links', result1.externalLinks?.toString() || '0', result2.externalLinks?.toString() || '0', (result1.externalLinks - result2.externalLinks).toString()]
        ];

        doc.autoTable({
            startY: yPos,
            head: [comparison[0]],
            body: comparison.slice(1),
            theme: 'grid',
            headStyles: { fillColor: [147, 51, 234] },
            margin: { left: 20, right: 20 },
            columnStyles: {
                3: {
                    cellWidth: 30,
                    halign: 'center',
                    didParseCell: function (data) {
                        if (data.section === 'body') {
                            const val = parseInt(data.cell.text[0]);
                            if (val > 0) {
                                data.cell.styles.textColor = [34, 197, 94]; // Green
                            } else if (val < 0) {
                                data.cell.styles.textColor = [239, 68, 68]; // Red
                            }
                        }
                    }
                }
            }
        });

        // Footer
        if (branding.footer) {
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(branding.footer, 20, 285);
        }

        doc.save(filename);
    }
}

export default new PDFExportService();
